name: Terraform Dev Validation

on:
  pull_request:
    paths:
      - 'overlays/dev/**'
      - 'modules/**'
  push:
    branches:
      - main

jobs:
  terraform:
    name: Validate & Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: overlays/dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init (Local Only)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan.out

      - name: Show Plan Output
        run: terraform show -no-color tfplan.out
